### ISSUE TITLE
[enhancement] Save images to hard disk

### ISSUE THREAD

**Issue by malenki** [mapillary/mapillary_issues#1167]
When making a longer journey by car, it is cumbersome to copy all the mapillary images from a micro SD to a hard disk drive all the time.
It would be a nice feature if mapillary could save images directly to a HDD  connected via OTG.

**Comment by peterneubauer** [comment]
Is the setting to change the storage dir not working for you?

**Comment by peterneubauer** [comment]
In the preferences you can set a custom Mapillary storage directory. We now implemented to actually check if the app can create files in that dir (a lot of areas are now forbidden to write to for normal Android apps). Closing this for now @malenki

**Comment by malenki** [comment]
Peter Neubauer schrieb
am Wed, 18 Nov 2015 01:38:10 -0800:

> In the preferences you can set a custom Mapillary storage directory.
> We now implemented to actually check if the app can create files in
> that dir

Thanks for remembering this.
I thought I had replied on your question in September but obviously
didn't. I do now:
~Three days after starting holidays (and about two weeks after
purchasing it) my phone had died and I afterwards sent it back for
refund. So I couldn't check the setting for the storage dir with the
app still not running on my Siemens ME45. :)

**Comment by utack** [comment]
Does not seem to work in Android 6
Should this be reported as a general "use storage access framework" or reopened OTG-specifically?

**Comment by peterneubauer** [comment]
Let me check to set a custom directory once I get into the office with an android 6 phone

**Comment by utack** [comment]
Custom directory works fine, but unfortunately all OTG drives are no more mounted in storage, they are only accessible through the storage access framework starting with Android 6

**Comment by ovivoda** [comment]
SAF support was added but SAF itself is still very slow, almost unusable for the application use cases

**Comment by ovivoda** [comment]
_mapillary_issues is no longer an active repository._

_Let’s continue discussing features in our forum! We will import this issue as topic to the <a href="http://forum.mapillary.com ">Mapillary Forum</a> in the coming weeks. We’ll notify here once it’s been done. See you there!_
