### ISSUE TITLE
Android app reports bad GPS signal untill killed

### ISSUE THREAD

**Issue by simonmikkelsen** [mapillary/mapillary_issues#1655]
I have used the Android app to take a sequence and want to start a new one. The GPS icon shows green, which other GPS apps agree with. But when I press the start button, the app reports that it is waiting for better GPS fix - the GPS icon is still green.

Workaround: Kill the app and start it again. Then it usually works.

See also http://forum.mapillary.com/t/android-mapillary-app-refuse-taking-pictures-bad-gps/335 where it is reported to start around a month ago.

**Comment by HolgerJeromin** [comment]
Same here while switching from osmand (or every other app)  to mapillary (which is in capture mode) . Leaving camera  mode and reentering works here.

**Comment by simonmikkelsen** [comment]
Quote from the forum thread:

Also Andriod issues version 169

I have noticed that accuracy info pane GPS in Mapillary (settings>Show detailed stats) is 2 times wrong when compared to GPS Status & Toolbox app stats

Mapillary GPS says for ex. 16 meter wrong accuracy but the GPS Status & Toolbox app says 8 meter accuracy.

Before Mapillary can take photos the info pane have to say 12 meter.

Best regards
Soren Johannessen

**Comment by peterneubauer** [comment]
Mmh,
we are getting the accuracy from the Google Location services or the GPS listener, nothing fancy happening there ...

**Comment by moenk** [comment]
As I already mentioned in the forums: The bug in the Mapillary app seems to exist since it is possible to enable the Google location services makes it nearly impossible to take photos any more. It does not help to disable this feature. When starting capturing everything works fine, after about one hour it starts to refuse the position fix.
I can not see any changes in satellite view in Locus, and Apps like Ingress shows the correct position on the map (also they use this services I think). Please fix that, it's really annoying to be in good mood for capturing when the sun is shining and the sky is blue and then the app refuses to do so.

**Comment by peterneubauer** [comment]
The GPS not being released correctly is now fixed in 1.71 coming out soon. The fix is disappearing after a while of driving out of the blue?

**Comment by jaakkoh** [comment]
I've experienced the same problem lately on my Galaxy Note 10.4 (2014) -- but I haven't noticed it on my Galaxy S5. I'm also a beta tester and at v.1.69 on both.

I usually experience the issue in driving mode (which is what I usually use) after I've stopped for a while. When moving again the app either notes that the speed is too low or then the coordinates are simply zeroed. Quitting the app and restarting (without any additional killing of processes) usually fixes the issue.

I don't (think that) I use the Google Location services in either of my devices.

**Comment by moenk** [comment]
I checked now the version 1.71 and the GPS seems to work now. However, I need to disable the Play Service, otherwise no picture is taken because the app states "too slow" (even while driving 60 km/h).

**Comment by HolgerJeromin** [comment]
I still have the issue a few days ago. Going into the mapillary setting and leaving trigger the bug. Leaving camera into main menu and reentering camera works here.

**Comment by jaakkoh** [comment]
I was able to overcome the problem already with v1.69 by just disabling the Google Play services. That is, while I claimed before that I didn't have the GP services on I in fact did -- and disabling it did the trick.

**Comment by skorasaurus** [comment]
Also receiving these issues intermittently over the past 2 days; haven't figured out how to trigger this. 
I'm on 1.75.... I'm sure that the GPS is working because I opened up another app (GPS Test) and reported a signal with accuracy of 10-15 meters... 

Here's some mapillary logs if it helps. 
https://gist.github.com/skorasaurus/0ceb5c123719c2b4ed94/edit

**Comment by rsahlin** [comment]
Hi
I will be looking into this issue - I will start by trying to reproduce the loss of location fix when exiting the application.
Will also investigate how google play location services are working.

**Comment by HolgerJeromin** [comment]
1.76 has still the problem here with my fairphone 2. 
icon is green, taking photos works.
going into the settings, leaving settings
icon is still green, debug output is happy, too. taking photos says: "i have no gps fix"

**Comment by rsahlin** [comment]
Thanks for checking - the 1.76 only includes fix for low GPS accuracy, ie the text displayed.
Will look into this issue tomorrow and try to reproduce with your instuctions.

**Comment by rsahlin** [comment]
Able to reproduce on Xperia Z2 Tablet, investigating now.

**Comment by rsahlin** [comment]
Version 1.77 hopefully fixes the 'no gps fix'.
Please either wait for Beta update or download directly from mapillary.com
Thanks

**Comment by HolgerJeromin** [comment]
Works here. Thanks

**Comment by rsahlin** [comment]
Great - many, many thanks for checking!

@simonmikkelsen Could you please verify that the issue as you originally reported it is fixed?

Thanks for your support :-)
Best regards
/Richard
