### ISSUE TITLE
Pictures do not upload

### ISSUE THREAD

**Issue by shlublu** [mapillary/mapillary_issues#1905]
Strange issue that is currently happening.

Mapillary 185, under Android 21 /  Galaxy S5.
Pictures just do not upload. Wifi is enabled, pictures are on the SD card and can be reviewed, and surprisingly, I don't have any notification inviting me to upload.

When I do, it seems that there is some wifi traffic for a short while but eventually nothing happens. 

It's not the first time I upload with this setup though. Any idea?

**Comment by rsahlin** [comment]
Hi @shlublu 

Could you please enable logs by going into 'Feed' - 'Settings' and checking 'Write trace logs'.
Select to upload your pictures, if needed wait for upload to stop.
Then go into 'Feed' and select 'Send debug logs'
This will provide us with the logs so we can investigate the problem

Best regards
/Richard

**Comment by shlublu** [comment]
Thanks @rsahlin,

I've just done that. And surprisingly the log says nothing wrong (no error, no exception), but "app.mapillary.android.sync.UploadService  - No files to upload ". Where I have 109 of them.

The reviewing feature is OK and allows me to review these sequences. The shortcut icon also shows a "109" sign written in white in an orange bubble.

In the logs, the preferred path points (seems to point) to my external SD card, which is fine: I do have one installed and this is where the pictures are stored by the app.

**Comment by rsahlin** [comment]
Attaching logs

[mapillary_trace (7).txt](https://github.com/mapillary/mapillary_issues/files/292801/mapillary_trace.7.txt)

**Comment by rsahlin** [comment]
When the app looks in:
/storage/extSdCard/Android/data/app.mapillary/files/mapillary
- It finds 109 images to upload - this seems to be fine.

When upload starts:
getDefaultImageStoragePath- /storage/extSdCard/Android/data/app.mapillary/files/mapillary
- No sequences or files are found.

**Comment by rsahlin** [comment]
The TrayAppPreferences in UploadService does not return any files that should be saved.
I will add debug logs to see what happens with the images after review.

**Comment by shlublu** [comment]
@rsahlin Ok, thanks! Please let me know once available, I'll restest and send you the logs.

**Comment by rsahlin** [comment]
Pllease install and run latest apk (app-release_current.apk) from here:
http://android-releases.mapillary.io/index.html

This will not solve the issue BUT it will print more debug information in the logs so that I hopefully can understand what happens.
Once installed, please trigger upload the same way as before and send the logs.

Thank you very much for your help and support!

**Comment by shlublu** [comment]
Done! Logs sent!

**Comment by rsahlin** [comment]
Hi Vincent and thank you very much - sadly these logs are for version 1.85

Could you please install version latest version - app-release_current.apk from:
http://android-releases.mapillary.io/index.html

Please let me know if there is a problem installing.

To check what version you are using - please go into 'Feed' - 'Settings' and the version number will be at the bottom.

Best regards
/Richard

**Comment by shlublu** [comment]
How strange!

I downloaded and installed the 217 yesterday (successful installation of course), and then I sent the logs. I'll retry tonight, but I'll first uninstall the production release.

**Comment by rsahlin** [comment]
Hi @shlublu 

You are probably correct, it is probably because the log is too short and the old data is still present.

Could you please do the following when testing, first checking the version number as described above, when you have verified that it is at least 2.17:

- Open 'Feed' - 'Settings' and check 'Write trace logs'
- Exit Mapillary
- Open the app, review pictures and press to upload
- Send debug logs

Thank you!
Best regards
/Richard

**Comment by shlublu** [comment]
Hi

I did that exactly in that order a minute ago. The version number is 217, that's fine.
I included your first name and the issue number in the email's subject field.

Talk to you soon :)

**Comment by shlublu** [comment]
OK, I see what happens. The "upload" checkbox is now unchecke by default, while it was not existing so de facto checked before. This is what makes the app not to find anything to upload. 

Unfortunately, you have to check all boxes one by one even if you use the "start upload now" entry of the main menu instead of the upload button of the review sequences page.

**Comment by peterneubauer** [comment]
You can also toggle all/none in the extended menu in the sequence list?

**Comment by shlublu** [comment]
Oh, yes, I didn't notice that. 

It would be cool to have a toast saying that nothing is selected when using the upload function though. If I thought there was a bug without this to be seen as obvious, other will do have the same problem :)

**Comment by rsahlin** [comment]
Hi @shlublu - good you found the reason for the upload problems :-)

Yes - agreed, it would be good to have some indication that no images are selected.
We will look into this, thanks for your help and support!

Best regards
/Richard
