### ISSUE TITLE
Web viewer: no full resolution is loaded anymore when zooming in on images

### ISSUE THREAD

**Issue by kaitu** [mapillary/mapillary_issues#2501]
### Basic information
* Platform: `Web`
* Version: `...` 
* System/Browser: `Firefox 52.0.1 `

### Steps to reproduce behavior

 1. View an image at full screen
 2. Zoom in
 3. The image remains grainy, showing more artifacts than the full resolution original

### Expected behavior
Wanted behaviour: full resolution is loaded

### Actual behavior
No full resolution is available anymore in the viewer

### Additional information
I understand this might have been a deliberate choice. I invite you to reconsider it at least in the blur editor: it's currently impossible to decide what needs blurring from is what already is blurred enough in the original image.

**Comment by ToeBee** [comment]
This only happens on recently uploaded sequences so it seems like something is going wrong in the back end processing after uploads. In my browser's dev console I am getting the following errors when I try to zoom in:
![image](https://cloud.githubusercontent.com/assets/348948/24303947/d11fa6e4-1085-11e7-8e81-a9ba2670f814.png)

**Comment by paulinus** [comment]
There was a metadata error that prevented the zoom from working for images uploaded after Mar 13. It is solved for newly uploaded images and we are restoring the metadata for images since Mar 13. All images should work by tomorrow.
Thanks for reporting!

**Comment by kaitu** [comment]
@ToeBee: thanks for investigating, I hadn't noticed that only affected recent sequences.
@paulinus: excellent, thanks for the quick fix.

**Comment by paulinus** [comment]
All metadata is restored now. Please let us know if you see it happening again. thanks!

**Comment by ToeBee** [comment]
This picture and the one immediately before it are still not working right. Others in the area seem to be ok. I think the browser console error messages are different though:
https://www.mapillary.com/app/?pKey=WYIP-VRW4cl0TMuW7h4poA&focus=photo

And console errors:
![image](https://cloud.githubusercontent.com/assets/348948/24324047/02e81586-114d-11e7-98e6-32be54823a1b.png)

**Comment by paulinus** [comment]
@ToeBee there is something cached on the server for those 2 images. The metadata is fixed, but the server remembers the old version. Will investigate. Thanks for checking it.
