### ISSUE TITLE
Order of photos in sequence is incorrect

### ISSUE THREAD

**Issue by zzptichka** [mapillary/mapillary_issues#2670]
### Basic information
* Platform: Android 7.1.2 on Google Pixel
* Version: 3.86 

### Actual behavior

Photos in my recent sequences come out rearranged. If you go to next photo in sequence it sometimes it jumps forward, sometimes it jumps back. Not a GPS issue. Photos are mapped correctly, it's the order that is messed up. As if timestamps are assigned incorrectly by the app/phone. 
I'm shooting with 20m distance-based capture.
See sample sequence [here](https://www.mapillary.com/app/user/zzptichka?lat=45.29866888133597&lng=-75.73542586925345&z=17&mapStyle=osm&pKey=ADDzwvaH4RDpne495tw6XQ&focus=map)

**Comment by chk1** [comment]
Mapillary 3.86
Xiaomi Redmi 4X Global
Android 6.0.1 based MIUI 8.2.18
64GB SD Card configured for Mapillary storage

I have the same issue with basically all longer sequences I took. Some images are already wrongly ordered when I review images from the app's Upload tab. File names (shown in the app title area above the image) and GPS locations are correct and in order, but when I switch between images it jumps.

After uploading the image order is messed up in the processed sequence.

Examples:
[sequence IDs `_2b8dnJy891jxkHt62IVwQ` and `_usSp56dt26P3nOCuD40aA`](https://www.mapillary.com/app/?lat=52.072588316985616&lng=7.007982926722349&z=17.794176574316253)
[sequence ID `p7F7tx4bqvjqR9No6lmP9g`](https://www.mapillary.com/app/?lat=52.05426148466137&lng=6.944987899900411&z=17&pKey=t9VOkMBGqWe1wdwj-YnkRw)

**Comment by hakuchi** [comment]
I also have this issue.
Something have changed in the last update, because on version 3.85(or was this 3.84) the photos are uploaded correct

**Comment by frodrigo** [comment]
Same problem
Android App : 3.86
LineageOS, Android 6.0.1, Galaxy Nexus
https://www.mapillary.com/app/?lat=44.825941252036046&lng=-0.5342307391028669&z=18.928371813780153&pKey=4HzBqthJG5BSamg0dH9osA&focus=map&menu=false

**Comment by eneerhut** [comment]
Hi all,

Thanks for reporting this issue. It has been fixed so make sure you're on 3.89.

I'll check with the team to see if previously uploaded sequences can be corrected. Sorry for the inconvenience.

**Comment by peterneubauer** [comment]
Yes, it might be possible to rearrange the sequences - the timestamp in the EXIF has been written wrong in some versions of the app. We are tracking this. Thanks!

**Comment by floscher** [comment]
Maybe [`YBBJPQajH1mI4aadmJCUXA`](https://mapillary.com/map/s/YBBJPQajH1mI4aadmJCUXA) is another example of this issue. Additionally to the incorrect order, the images are also upside down.
It could be that it's a separate issue, because the images have been taken with a GoPro according to the Mapillary API, but I first wanted to comment here in case it's the same issue.

**Comment by chk1** [comment]
I recorded two sequences with app version 3.89 yesterday, it looks like the issue is still there for me. The first sequence of 125 images was fine, but the 2nd has images sorted wrong again, starting somewhere in the middle of 250 images I get time jumps again. 

I've not uploaded this track yet, images are sorted wrong on my phone like with the sequences before.

**Comment by peterneubauer** [comment]
@chk1 could I maybe get access to that sequence? Would love to examine it.

**Comment by chk1** [comment]
@peterneubauer 
I guess the bug is only present in the app gallery now, the processed sequence looks good!

Here's a [link to one of the images in the sequence](https://www.mapillary.com/app/user/chrki?lat=51.92645449999998&lng=7.629118299998595&z=17&feedItem=user-VYZPUOEvg2jR31jkMFSjzg-activity-user-VYZPUOEvg2jR31jkMFSjzg-publishing_done-image&pKey=2rhb06_N2lwVq3027V7LRQ&username%5B%5D=chrki&focus=photo) where I remember the jumps happened, a few images forward I think. As I said, the processed sequence is correct, but I noticed jumps in the upload tab / review part of the Android app. I will try taking a few more sequences later.

**Comment by peterneubauer** [comment]
Ok, closing this for now then, thanks @chk1 !

**Comment by chk1** [comment]
@eneerhut 
You mentioned you were working on correcting existing sequences, can you tell me if this is still a work in progress? 

I noticed that "sequence_cut" split some of my sequences, but I still have a lot of images in wrong order. I'm considering deleting some of the wrong image sequences and doing them again with the new app versions, unless there's some way to fix the sequences at some point in the near future. Thanks

**Comment by eneerhut** [comment]
@chk1 seems to be a harder fix then we initially thought. We'll continue to work on it, but for a shorter term solution, it's best to delete the sequences and remap if possible for you.

Apologies for the inconvenience.

**Comment by peterneubauer** [comment]
Yes, we are working on this. However, the wrong dates affect all Android versions 3.83-3.86. We cannot get the affected images by Android version from our Postgres database backend since they are stored in an Hstore column which is VERY slow to query ( and it's a couple of million images involved). So, we will add the app data to a faster store (even for future use) and query from there when that migration is done.

**Comment by peterneubauer** [comment]
related to https://github.com/mapillary/mapillary_issues/issues/1107

**Comment by peterneubauer** [comment]
So, images taking with Android 3.86 have now been reprocessed, most of these sequences look good now. Closing, let me know if anything is popping up.
