### ISSUE TITLE
Web: not all uploads are shown in list

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#2795]
The scrollable list of uploads in the profile sidebar on the web map, does not show all uploads.

For example, my sequences gKxjbbkQnCoV1ERzgZQ-Jg, 4e01T9jBvFL5chr_CFnQng, uUPCyh19XIF1FZMZFKNtaA, EWcV068Hfn0tVqBN_bdVXg, zPtm_-B9rh8KXxDyCqGvfQ do not show up in my upload list. (URLs: https://www.mapillary.com/map/im/mW-KJfIk2BQNXu0a6D0n8A, https://www.mapillary.com/map/im/wcbPyKHSldMxPQOApWwH2A, https://www.mapillary.com/map/im/PHLskVUlKxBiTyy6bbJGmA, https://www.mapillary.com/map/im/tCQfFl85Yz0t1M-vJBgXrw, https://www.mapillary.com/map/im/WzguooFg_suPmr4TPOeBJA)

Also, they are hidden from the map when I filter on only showing my uploads.

As an added problem (but maybe unrelated) the next sequence, ppVer0kROp-_dnYHVL4nPQ (URL https://www.mapillary.com/map/im/M3FbAL102ZrP0U_KX6aSxQ) shows several gaps when zoomed in on the map.

They have been uploaded a long time ago, so they should be completely processed by now.

**Comment by gyllen** [comment]
@peterneubauer Can you elevate?

**Comment by peterneubauer** [comment]
This is due to an error in the update of the capture date of the sequences. Triggered a data refresh for this.

**Comment by peterneubauer** [comment]
Should be fixed now.

**Comment by pbb72** [comment]
Hi @peterneubauer , could you detail what exactly has been fixed? Because it looks to me all mentioned sequences still don't show up in my uploads list, and still hide when showing only my own uploads on the map.

The final sequence however, that was not showing up completely, is fixed.

**Comment by peterneubauer** [comment]
@pbb72 is https://www.mapillary.com/app/user/pbb?focus=photo&pKey=wcbPyKHSldMxPQOApWwH2A&lat=50.13664016999843&lng=14.369428800000037&z=17 still not showing up in your feed? I checked the seqeunce and it seems very normal to me - fully processed and all.


As for https://www.mapillary.com/map/im/M3FbAL102ZrP0U_KX6aSxQ - this looks like small gaps due to the app not recording these images for some reason, e.g. bad GPS or so.

**Comment by pbb72** [comment]
Yes, https://www.mapillary.com/app/user/pbb?focus=photo&pKey=wcbPyKHSldMxPQOApWwH2A&lat=50.13664016999843&lng=14.369428800000037&z=17 is still not showing up in my feed.

Could you perform the following test?
1. Confirm (for yourself) that https://www.mapillary.com/app/user/pbb?focus=photo&pKey=wcbPyKHSldMxPQOApWwH2A&lat=50.13664016999843&lng=14.369428800000037&z=17 is indeed a sequence by user "pbb", as are several other sequences in the area.
2. Select https://www.mapillary.com/app/?focus=map&pKey=3TpgZrI6Acl3WQrlWBCzDg&lat=50.13574433850633&lng=14.371807268409839&z=14 (which is not by "pbb"), to make sure all "pbb" sequences are now unselected. Zoom out enough for the "pbb" sequences in the north-east to be visible.
3. Open the Filters menu, and enter user "pbb".
4. Notice how several of the sequences disappear, even though they are by "pbb".

**Comment by peterneubauer** [comment]
So,
this is an issue where the sequences are not rendered in certain zoom levels? cc @ptpt

**Comment by pbb72** [comment]
I'm not sure how to explain this the clearest.

* This concerns **at least** the following consecutive sequences: gKxjbbkQnCoV1ERzgZQ-Jg, 4e01T9jBvFL5chr_CFnQng, uUPCyh19XIF1FZMZFKNtaA, EWcV068Hfn0tVqBN_bdVXg. There might be many more, but they're difficult to discover.
* The sequences are missing **both** from the uploads timeline, and from the map when only showing my own uploads. This may be coincidence, or it may be technically related, I do not know.
* The map issue occurs in **all** zoom levels beyond 5. (5 and lower is too low resolution to see if it's affected.)
* As I see it is difficult to communicate the issue, it **may** be something only I am seeing, though it does happen also when I log into other computers, and when I browse anonymously.

Sequences on the map, without filtering:
![clipboard image 5](https://user-images.githubusercontent.com/1436366/34718296-694f2710-f536-11e7-9a43-23c11abc2ce1.png)

Showing only my own sequences, which **should** include them:
![clipboard image 6](https://user-images.githubusercontent.com/1436366/34718326-7ef0157a-f536-11e7-852f-cb6931e0b87f.png)

Also missing at low zoom levels:
![clipboard image 7](https://user-images.githubusercontent.com/1436366/34718362-a305fd8a-f536-11e7-96ce-208c27c54d82.png)

Sequences are also missing from the timeline:
![clipboard image 4](https://user-images.githubusercontent.com/1436366/34718421-d82120b2-f536-11e7-9c65-269fa0b1aabb.png)

(Which, by the way, is a horrible user experience. Is there really no other way to browse back then to scroll down for ten minutes, in a continuously further slowing down browser?)

**Comment by gyllen** [comment]
@ptpt Can you check these tiles?

**Comment by peterneubauer** [comment]
Ok I think @ptpt found an inconsistency in one of our databases. Going to track that down, and will report back.

**Comment by peterneubauer** [comment]
l

**Comment by peterneubauer** [comment]
This should be working now, let us know if not. Closing.

**Comment by pbb72** [comment]
Yes, it is working well now. Thanks for the follow-up.
