### ISSUE TITLE
Can't upload a big sequence

### ISSUE THREAD

**Issue by tobecwb** [mapillary/mapillary_issues#2799]
### Basic information
* Platform: `Web`
* System/Browser: `Windows/Google Chrome 62.0.3202.94 x64`

### Steps to reproduce behavior

 1. Use mapillary_tools to upload a sequence of images (more images, "better")
 2. Access the URL https://legacy.mapillary.com/map/upload/im
 3. Open Developers Tools on Google Chrome (F12)
 4. See a 504 error when browser request the status upload

### Expected behavior

Show a list of uploaded images to approve

### Actual behavior

A loading message with the following text: 'We are checking your current uploads on the Mapillary server.' that never finish

### Additional information

This occur more frequently on huge sequences (tested with a sequence of 6k images, but on small sequences - less than 100 images - this occur sometimes too)
Trying to aprove a uploaded sequence for more than 3 days. Always receiving the 504 error

**Comment by gyllen** [comment]
@tobecwb In general we never recommend sequences that are bigger than 1k images. In fact if you use our uploads script we will cut the sequences to be around 1k per sequence.

**Comment by tobecwb** [comment]
So, whats the solution?
I can't longer delete the sequence, because any operation on legacy dashboard return a 502 error.

And If you read, this sometimes occur even with smaller sequences (100 images or less)

**Comment by gyllen** [comment]
@tobecwb Let me check your folders in our system. What is your Mapillary username?

**Comment by tobecwb** [comment]
The username is "projevias". You can delete all photos that are in queue If you want

**Comment by gyllen** [comment]
Ok I checked your folder and it looks like you had `17520` images uploaded in the same sequence. I deleted this folder. Try a smaller upload now. Make sure that you `ack` the upload before you do a new one. Let me know if this works for you.

**Comment by tobecwb** [comment]
now legacy webpage works again! I will use shorter sequences, but still, I don't see this a solution.

Suppose that in my company, several employers can upload images on the same account on Mapillary (this is the case here). If every sector (differents roads) of company upload images on same day, nobody can't use Mapillary legacy anymore to approve sequence. I don't get why I have to ask here to you delete the photos, but great that you did;

Sure I can create a different account for every sector / project, but is very easy to get a sequence with more 1k photos here (on a single project, we has more than 30k photos of a single sequence).

I'm just a developer here, but for me, I think that Mapillary is a great plataform, but not ready for developers and/or integration with internal projects. Like I said on another github project, no documentation at all, and no way I can automate some steps.

**Comment by Alessandro-Barbieri** [comment]
>In general we never recommend sequences that are bigger than 1k images. 

Why it's not documented?

>In fact if you use our uploads script we will cut the sequences to be around 1k per sequence.

Which script? There are many and at least one is not doing what you say. Please provide better documentation.

**Comment by gyllen** [comment]
@tobecwb Thanks for the feedback. 

It would be interesting to know more about your workflow for your company and we will probably be able to setup you with the right tools to upload, do you use the Mapillary Apps (iOS and Android) to capture or do you use something else. Many people are at the moment using https://github.com/mapillary/mapillary_tools/tree/master/python for uploading. The script `upload_with_preprocessing.py` is very competent and your best bet, it will cut sequences at 1000 images automatically for you.

@Alessandro-Barbieri Thank you for your voiced concern. 

As you maybe understand we are a small team that is trying to fulfill a lot of different demands at the moment. That we are weak on documenting and giving the right tools for uploads outside the Mapillary apps is a concern that we are well aware of inside the team. As we see a growing demand for uploads outside of the apps we also see this as one of our main focus points.

As the architect for the platform I have also seen the current way of uploading outgrow us. We need a more "user friendly" API for uploading and we also need a faster way to upload (at the moment all files have to be uploaded directly to Ireland (this is slow for somebody in Australia)).

Therefore we are at the moment trying to figure out how this API should look like. This is also one of the main reasons I am hesitant on clearly displaying somewhere how our upload API works (we do not want to get stuck with a legacy API). 

If you have any feedback regarding the old API I would gladly take it here or setup a Skype call if you have more than can fit on this page :).

In the longer run we have plans on building a desktop uploader (its really not optimal to upload TB of data through the web). We have been bouncing this idea around for a while and my thoughts are.

1. Figure out what is the best base level API
2. Adjust and document the open sourced Mapillary Scripts around the new base level API
3. Create an open source interface (probably in atom), that lives on top of the folder structure generated from the scripts and use a queuing system to start and track the scripts from this interface.

@tobecwb @Alessandro-Barbieri To reiterate your feedback is greatly appreciated from the the whole team

**Comment by Alessandro-Barbieri** [comment]
`upload_with_authentication.py` and `split_sequence.py` never split sequences at 1000 images (from my experience). Tomorrow I'll use the other script and report back.

**Comment by Alessandro-Barbieri** [comment]
Why I'm having this workflow?  I'm not using android app because of #2777 #2174 #627

**Comment by tobecwb** [comment]
> It would be interesting to know more about your workflow for your company and we will probably be able to setup you with the right tools to upload, do you use the Mapillary Apps (iOS and Android) to capture or do you use something else. Many people are at the moment using https://github.com/mapillary/mapillary_tools/tree/master/python for uploading. The script upload_with_preprocessing.py is very competent and your best bet, it will cut sequences at 1000 images automatically for you.

I really don't used the `upload_with_preprocessing.py` here. Only to test a small sequence, and how to upload the files to the Mapillary Server. Your solution don't fit very well in your workflow.

I'm using in this way:
https://gist.github.com/tobecwb/9c43b88f4caa2484c8086d8d01648b23

Currently, we are using ESRI ArcMap, so, I developed a Python Toolbox. Why? We have several projects. Some projects has more than 100k photos. Not everybody here know Python, but everybody know ESRI ArcMap, so, a Toolbox appear to me a friendly way to the users send a sequence without use a terminal or write anything (believe-me, some people are afraid to use a terminal window). 
Secondly, using ESRI ArcMap, they can filter what images to upload using several filters, not only by distance, but date, angle, type of camera, direction, by address, etc... 

We don't use IOS or Android Application. Most of the times, we do Videos with cameras like GoPro and VIRB, and imajbox (http://imajing.eu/mobile-mapping-solutions/mobile-mapping-system-imajbox/).
Imajbox generate a image sequence, then, with ArcMap, the EXIF is inserted on images (using my script), and then uploaded do Mapillary Server (again, using my script, everything inside in ESRI ArcMap).

For videos like GoPro and VIRB, I developed another script that convert the frames of the video to image, and do a interpolation with GPS data from Imajbox (currently, we don't use this yet).

> Therefore we are at the moment trying to figure out how this API should look like. This is also one of the main reasons I am hesitant on clearly displaying somewhere how our upload API works (we do not want to get stuck with a legacy API).

Like I said on another github project (I believe in mapillary_tools issue), for me, a REST server, with a good documentation, is a perfect solution, at least for me.

Take a look on the documentation that I made: https://gist.github.com/tobecwb/9c43b88f4caa2484c8086d8d01648b23.

It's not perfect, but considering the little information (no documentation), it's the best I can do.

> In the longer run we have plans on building a desktop uploader (its really not optimal to upload TB of data through the web). We have been bouncing this idea around for a while and my thoughts are.
> 
> Figure out what is the best base level API
> Adjust and document the open sourced Mapillary Scripts around the new base level API
> Create an open source interface (probably in atom), that lives on top of the folder structure generated from the scripts and use a queuing system to start and track the scripts from this interface.

I don't think a desktop uploader it's a priority. I still believe that you must provide a way that every developer can adapt the workflow of the company to use Mapillary services. This is different than change all your workflow to use your service. Peoples stop to use a service that require to much changes. With a good API, developers can to solutions that can be adapted for every workflow.

**Comment by gyllen** [comment]
@tobecwb `With a good API, developers can to solutions that can be adapted for every workflow.` Exactly this is the first step. 

One thing about the API though is that it will always be direct against S3, we handle millions of uploads per day and having the confidence of the S3 infrastructure to rely has served us really well so far.

I will keep you updated about our work and might toss some ideas in here too.

**Comment by cbeddow** [comment]
@tobecwb Are the images always in a sequence? You need a way to logically split them into sequences, but make sure they are groups of points, so not a sequence where some images are on one street, and others across the city, with a gap in between.

I would recommend that once the script runs, you put the image OIDs into an array, then select array objects 0 to 999, and group them into a folder, then do the same for each 1000 photos, and the remainder go in a last folder. The idea here is simply to prep the uploads in separate folders of maximum 1000, instead of 17000 or so as a single upload. You can build this into the script, or you can do this beforehand and then run your scripts as a batch process on several layers, of 1000 images maximum per point layer. 

Does that seem to help? Our Mapillary python tools scripts may be an inspiration, you can freely opy code from them to do this.

**Comment by tobecwb** [comment]
> @tobecwb Are the images always in a sequence? You need a way to logically split them into sequences, but make sure they are groups of points, so not a sequence where some images are on one street, and others across the city, with a gap in between.

Yes, they are in sequence (I known by filename - sequential, and date on EXIF)

> I would recommend that once the script runs, you put the image OIDs into an array, then select array objects 0 to 999, and group them into a folder, then do the same for each 1000 photos, and the remainder go in a last folder. The idea here is simply to prep the uploads in separate folders of maximum 1000, instead of 17000 or so as a single upload. You can build this into the script, or you can do this beforehand and then run your scripts as a batch process on several layers, of 1000 images maximum per point layer.

I already to that after @gyllen says to split the sequence by 1k images (but to be on safe side, I reduced this to 400 on a big sequence just to test).

**Comment by cbeddow** [comment]
Oh great! Let us know how it is working then, sounds like a nice workflow
at this point.

**Comment by Alessandro-Barbieri** [comment]
upload_with_preprocessing.py creates sequences long max 1001 images

**Comment by tobecwb** [comment]
again I'm having this issue
it's horrible to depend of somebody else just to 'press a button to publish' or 'discard'!

I can say that it's my fault this time. A employeer uploaded several images without my acknowledge, but every sequence has no more than 400 photos... last time I can get to aprove the sequences, I see that my user ( `projevias`) has 33 sequences to aprove (every sequence with 400 photos)
and again, I must ask somebody else only to approve all the sequences, so I can continue with the upload process

**Comment by GITNE** [comment]
> …again, I must ask somebody else only to approve all the sequences, so I can continue with the upload process

@gyllen Right, please add a checkbox or `Upload & Publish` button to indicate to the uploader to publish automatically when upload is complete (no more images left). This is especially useful to users with long running unattended uploads.

**Comment by tobecwb** [comment]
no updates on this? we stopped to send images until this is ok :(

**Comment by gyllen** [comment]
@tobecwb So what you need is a tickbox that would automatically approve after succesful upload.

**Comment by tobecwb** [comment]
I need two things.
- aprove all the photos that are in 'queue' of user `projevias`;
- if this option with tickbox works with script upload, yes, if not, I need a option to aprove automatically uploaded photos using scripts;

**Comment by Alessandro-Barbieri** [comment]
`upload_with_preprocessing.py` have the `--auto_done` feature

**Comment by tobecwb** [comment]
@Alessandro-Barbieri good to know!
But still, I can't upload anything on my user until all the previous photos have not been approved.
To many photos to aprove, and the server always respond with `504 error`

**Comment by tobecwb** [comment]
so...?
i have to stop the use of the Mapilllary?
more than one month, and I can't upload anything yet. :(

**Comment by gyllen** [comment]
@tobecwb I see about 45 sequences uploaded none of them are confirmed. Do you want me to confirm all of those?

**Comment by tobecwb** [comment]
yes, this is exactly what i need! tks

**Comment by gyllen** [comment]
ok started with 2 sequences, can you check in like 30 minutes or so that this is what you want

**Comment by tobecwb** [comment]
I still can't continue uploads.
everytime I try to use the https://legacy.mapillary.com/map/upload/im to approve any pending upload, the server respond with a `504 Gateway Time-out` on `https://a.mapillary.com/v2/me/uploads/status?client_id=xxxxxxx`

**Comment by gyllen** [comment]
@tobecwb Does the 2 sequences look correct though? Once you confirmed that I will send the other 42 through the system again.

**Comment by tobecwb** [comment]
Checked the sequences, and everything seems to be ok!

**Comment by gyllen** [comment]
@tobecwb Ok all sequences should be going through system now. Let me know how they look for you.

**Comment by tobecwb** [comment]
tks @gyllen 
It's working again!

**Comment by gyllen** [comment]
@tobecwb Yey! And old sequences are in good shape?

Also let me know if there is anything I can help you out with for future uploads!

**Comment by tobecwb** [comment]
And again I have this problem.... 
and this time I'm using the Mapillary Tools (python) with damaged all images :(

I was trying to upload something like 183.000 images, and this time I used the `upload_with_preprocessing.py`.

Used the following command:
`python upload_with_preprocessing.py` d:\images_to_upload_dir --remove_duplicates --auto_done`

after several hours scanning all files, the images was divided in several folders, and upload the begin
after some days, the upload script was stuck, with following error:
`
Exception in thread Thread-630:===========================---] 95.7% ... 43 images left..
Traceback (most recent call last):
  File "c:\python27\arcgis10.5\Lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "D:\dev\mapillary_tools\python\lib\uploader.py", line 48, in run
    upload_file(filepath, **self.params)
  File "D:\dev\mapillary_tools\python\lib\uploader.py", line 276, in upload_file
    response = urllib2.urlopen(request)
  File "c:\python27\arcgis10.5\Lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "c:\python27\arcgis10.5\Lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "c:\python27\arcgis10.5\Lib\urllib2.py", line 447, in _open
    '_open', req)
  File "c:\python27\arcgis10.5\Lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "c:\python27\arcgis10.5\Lib\urllib2.py", line 1241, in https_open
    context=self._context)
  File "c:\python27\arcgis10.5\Lib\urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "c:\python27\arcgis10.5\Lib\httplib.py", line 1136, in getresponse
    response.begin()
  File "c:\python27\arcgis10.5\Lib\httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "c:\python27\arcgis10.5\Lib\httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "c:\python27\arcgis10.5\Lib\socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "c:\python27\arcgis10.5\Lib\ssl.py", line 756, in recv
    return self.read(buflen)
  File "c:\python27\arcgis10.5\Lib\ssl.py", line 643, in read
    v = self._sslobj.read(len)
[============================================================] 100.0% ... 0 images left.
`
now, I checked the images on folder, and all images are garbage (no real images, only "noise").
using `legacy.mapillary.com` to see if anything was uploaded, the server always respond with 502 error (the `--auto_done` option doesn't work?)

**Comment by tobecwb** [comment]
anybody can delete all uploaded images that I send on this month?
I believe that the mapillary_tools (upload_with_preprocessing.py) only uploaded garbage images

**Comment by gyllen** [comment]
@jernejaMislej Can you help out with understanding what happened here. I don't see how the images could have been garbled in any way.

**Comment by jernejaMislej** [comment]
@gyllen i ll have a look, but for a while there was a bug occurring on windows only, which is now fixed, but that bug did mess up the image, see this issue https://github.com/mapillary/mapillary_tools/issues/217

**Comment by tobecwb** [comment]
Yes, I'm using Windows, and the bug is relationed with bug mentioned by @jernejaMislej, but the solution don't worked for me! I'm still checking what's wrong (I update piexif and everything and the bug still remain). But for now, I just only need that somebody delete all images I have uploaded in this month.

After that, I can check the bug on mapillary_tools and report on there if needed.

**Comment by gyllen** [comment]
@tobecwb Are you able to manually delete your own images or are there too many seuqnces for you to delete?

**Comment by tobecwb** [comment]
Like I said, I can't login do legacy.mapillary to delete any images, because has too many sequences.. (and I believe all images are garbage because of bug on piexif for windows).
The server always respond with a 502 error (this always occur when has too many sequences to approve).

on mapillary.com, the sequences don't appear, so, I believe that the `auto_done` function doesn't work

So, there's no way I can delete my images. Somebody on mapillary must delete for me :(

**Comment by gyllen** [comment]
@tobecwb I see `158` sequences that you have _not_ acknowledged, should I delete all of those?

**Comment by tobecwb** [comment]
yes, you can delete all 158 sequences if possible!
tks

**Comment by gyllen** [comment]
Ok deleted ~150k images

**Comment by Alessandro-Barbieri** [comment]
autodone works at the end of a successful uoload

**Comment by tobecwb** [comment]
@Alessandro-Barbieri after upload all sequences? or after every sequence? If I'm not wrong, I had something about 10 sequences with fail, but more than 100 sequences with "success" (disregard the garbage images), and got any sequence with `auto done`.

**Comment by Alessandro-Barbieri** [comment]
Your command exited cleanly? On the output it says something about autodone

**Comment by tobecwb** [comment]
the output it's on this post: https://github.com/mapillary/mapillary_issues/issues/2799#issuecomment-365643327 (the script was stuck on this screen... I have to press ctrl+c to finish).

so, if I understand correctly, the `auto_done` works after all sequences has finished, correctly?
if I has 100 sequences, and 1 sequence has failed, the auto_done don't mark the 99 sequences as 'done'? (this is my case)

**Comment by gyllen** [comment]
@cookry @jernejaMislej Can you guys help out here ^^^

**Comment by Alessandro-Barbieri** [comment]
@tobecwb yes, you have to write a bash script that iterate on every folder and then upload in order to minimize the chance of failure

**Comment by ybkuang** [comment]
@jernejaMislej I pushed a change in a branch https://github.com/mapillary/mapillary_tools/tree/feature-sequence-done, will be great if you can help double check.

**Comment by bob3bob3** [comment]
@gyllen Am confirming that using upload_with_authentication.py one should limit to maximum 1k images per sequence? I have a few million tagged images of Australia driving last 2-3 years to upload. username is bob3bob3. only tested 3 small sequences to date.

**Comment by ybkuang** [comment]
@bob3bob3 let's try to figure out a way for you to upload for such a large volume of data. One option can be that we make custom script for you if you can share with us the folder structures.

**Comment by bob3bob3** [comment]
@ybkuang Have about 24,000 tagged and ready to upload, but can only do so at low Internet cost locations. I will be at the next location on Friday 25th May. Will use existing scripts for that with 1000 max per seq.

Ideally I'd like to use rsync, but am flexible. In future will park vehicle near WiFi spot and upload in batches. Structure at moment is 10 day date folders with no subs. eg 2018-052, 2018-051. This is not a good system as the number of images files is large. I will change to a daily directory as I imagemagik process and remove those less than 18KPH. Each folder (eg 20180522, 20180521) will have between 500 and 4000 images.

This processing will take some time which is why I am considering just using the existing tools.

**Comment by ybkuang** [comment]
@bob3bob3 `upload_with_authentication.py` does not support the max-sequence length case. Can you take a look at the `upload_with_preprocessing.py` for this purpose? 
```
python upload_with_preprocessing.py image_path --auto_done
```
will do the trick. It does not support processing of sub-folders, so you may have to make a bash script to loop through all your folders (2018-052, 2018-051 ..).

We are working on optimizing the workflow for the upload tools current. There will be a new release soon to address some these issues (cc @tobecwb )

**Comment by bob3bob3** [comment]
@ybkuang I am ready to try upload_with_preprocessing.py I assume that --skip_upload is a good argument to test with? One of my concerns is that I would like to start a large upload as I have access, stop, then continue at a later date.

Is the default for --interpolate_directions disabled? My images already have that data.

I realise some maintenance work may have slowed my 26K image uploads 2 days ago, but I am not seeing the traces on the web GUI. Does it take a few days to appear?

**Comment by bob3bob3** [comment]
@ybkuang Seems to be working fine thanks. Have uploaded about 10K using this method. Another 75K to go with this session. The script did fail at one point something about unable to allocate thread. I had set MAX_THREADS to 8 so perhaps I was asking too much!

Am concerned though that zooming up on my tracks, some segments eventually disappear until I go write down to street blob level and wait a while. (web interface Firefox)
