### ISSUE TITLE
Android app shows no recording progress

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#668]
I've had many situations with the old app where recording stopped unintended.

Sometimes, it would just end recording mode. I don't know if this happened because of me touching the screen accidentally, or because of bad GPS reception, or because of a bug, but it required me to regularly check the screen to see if there was a red square (meaning recording was active) or a red circle (meaning recording was not active).

However, many times even when recording was active, it was not actually taking pictures. Maybe because of bad GPS receiption, or me holding the screen too lopsided. So I started regularly checking the number of pictures taken to see if that was increasing.

Now, the new app has no way to see if anything is actually being recorded, short of exiting the camera screen, opening the menu, and checking the number in the review queue. As a result (and maybe because of an bug in the autoshot mode), I only recorded 27 images during an hours walk, and I have no clue what went wrong.

Ideally, the camera would have a clear (big, high contrast!) status symbol that shows one of the following states: recording, manual pause, facedown pause, no movement detected, shake pause, tilt pause, insufficient GPS reception.

Alternative could be a (big, high contrast!) counter for the number of images taken in this sequence, visible in the camera screen. That way I can check myself if anything is being done.

**Comment by blajo** [comment]
I used the new app for the first time today. I drove my car and recorded for about 20 km, when I came back it uploaded the images and the result was 3 sequences of 30 images each? The result should have been a couple of thousand images divided on 4 sequences. 
What I could see it looked like the app was recording properly the whole time. I'm using a Oneplus One phone.

**Comment by peterneubauer** [comment]
Yes,
That bug us fixed in the latest update 1.07,super sorry for that Johnny!

**Comment by blajo** [comment]
To bad it was great weather to catch good images today. I've now updated to 1.07.

**Comment by peterneubauer** [comment]
Let me know if the problem is fixed now. Sorry again!

**Comment by pbb72** [comment]
No, the problem is not fixed. I upgraded to 1.07, and there is still nothing that shows recording activity on the camera screen. You still have to exit the camera and check the review queue to see if photos have been recorded.

**Comment by polarbearing** [comment]
While I am looking for getting the shutter sound less annoying in #646, would it help in your case if you switch it on?

**Comment by peterneubauer** [comment]
Have added a sequence number counter in the next release.

**Comment by pbb72** [comment]
You're correct, the shutter sound is a good indication of recording progress. But as I am taking my sequences walking, I feel a bit embarrassed to be obviously photographing all and everything ;-) A shutter sound every 5 seconds would not make things better. However, I could of course bring a headset, I will try that!

**Comment by peterneubauer** [comment]
Added a counter in the next release.
