### ISSUE TITLE
*MUST* have a way to disable auto new sequence

### ISSUE THREAD

**Issue by naoliv** [mapillary/mapillary_issues#692]
Imagine how frustrate (and a lot more negative words) somebody who plans a trip, buy a new phone support and calculate the interval to take pictures (to fit in the phone memory) can get after seeing that Mapillary has failed to take photos.

I have configured Mapillary to take pics at each 6 seconds, but for my surprise it seems that 300 meters (the maximum value from "New sequence" option) is reached before a new pic is taken (and then Mapillary creates a new sequence and just stops to take new pics). Nice! Really nice! I mean, I am so happy for this. 5+ hours of travel that wasn't captured.

After frustration and taking a look at the config it seems that we basically have this:
* set min distance to 0 and mapillary will take only one pic, start a new sequence and you will not have anything else captured (unless you keep clicking to start the new sequence)
* set min distance to 300 (how did you choose this value?) and pray to be lucky and have a pic taken before 300 meters is reached (otherwise Mapillary will, again, start a new sequence and not start automatically capturing data).

It should not matter the distance nor time nor anything else to keep all my pics in the same sequence.
Mapillary should also not just stop taking pics like this. I can't drive and look at the phone at the same time to see what Mapillary is doing.

Not happy...

**Comment by naoliv** [comment]
"don't stop while auto-breaking sequences"
It seems that I won the prize to use it just before this fix...

**Comment by naoliv** [comment]
Actually I will reopen this. Is it really necessary to create new sequences at each X meters?

**Comment by peterneubauer** [comment]
Really sorry man, this should be working now when the new version is out.

**Comment by pbb72** [comment]
Is this a duplicate of #682 ?

**Comment by peterneubauer** [comment]
Why would you have sequences with gaps more than 300m?

**Comment by naoliv** [comment]
Because it's the same sequence, but with a bigger distance between the images.
Suppose I can take only one pic at each 10 seconds. Travelling at 100 Km/h (27.77 m/s) theoretically I will have one pic at each 277 meters. But then, the phone shakes and I miss the 300m threshold.
Why would the next pic (at 500+ meters) be considered a new sequence? For me it's still the same sequence (same trip), no matter if I could perfectly take all my pics at 270 meters or if I missed some.

**Comment by kaitu** [comment]
Another case where I reckon it will cause unwanted fragmentation is along roads running  through plenty of tunnels.

**Comment by peterneubauer** [comment]
Still, these sequences would potentially have a gap drawing straight lines for several hundred meters. I don't like
WDYT @gyllen @jesolem ?

**Comment by jesolem** [comment]
That would look really bad. Photos with 300m gaps are not really a useful sequence.

**Comment by peterneubauer** [comment]
Close it?

**Comment by polarbearing** [comment]
And I don't like straight lines drawn over a tunnel. My intention is to capture tunnels with interpolated positions driving at constant speed with cruise-control on. Straight lines over tunnels would clutter those specific efforts.
