### ISSUE TITLE
866 lost images found, can not upload them

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#809]
I have "Upload pictures in background" turned OFF, because I want to check my images before I upload them.

But several times, I've had the feeling that the images in my review queue had disappeared even though I hadn't uploaded them. Checking the website didn't show them as uploaded either.

This morning it happened again, and I decided to see what I could find out. As it turns out, even though my review page is empty, the Mapillary folder on my phone contains 866 images in 45 folders, one folder for each disappeared sequence.

That is A LOT of images that were gone. But now that I've found them, how can I upload them? The manual upload on the website doesn't accept them because of missing EXIF data. Can I make the app put them in the review page again?

**Comment by rudolfmayer** [comment]
I once use the upload script successfully: http://blog.mapillary.com/technology/2014/07/21/upload-scripts.html

**Comment by peterneubauer** [comment]
Mmh, where were these folders located? The app should pick up folders under the main file directory and display anything in there as images.

**Comment by pbb72** [comment]
Oh! I see now these photos are stored on the internal memory. Could it be that the app sometimes has difficulty finding the external SD storage, then automatically switches to internal storage, and then switches back to SD storage when it is able to access that? And in the process "forgetting" about the images that were stored on internal storage?

**Comment by HolgerJeromin** [comment]
As i wrote in https://github.com/mapillary/mapillary_issues/issues/706#issuecomment-75531633
Mapillary should look (and upload/delete) for images in 
/data/data/app.mapillary/files/mapillary
even if it is using another path right now.
This should be fixed!

**Comment by peterneubauer** [comment]
Well, the problem is that different devices have different file layouts. if an external storage is found, we try to use that one. In order to upload the images, just move them under the current data directory with e.g. a file manager, should work.

**Comment by pbb72** [comment]
Thanks, I moved the files and they were found and uploaded!

But the app should detect this. Maybe write the last save location in a config/registry somewhere, so that the app can notice the location is not available anymore. Then later when the default location is available again, continue to upload also photos from the backup location if they still exist there.

**Comment by peterneubauer** [comment]
Mm true,
Or maybe document where to look.

**Comment by HolgerJeromin** [comment]
I would vote against pushing this to the user. This path is not the easiest string to remember and find in a filemanager (for Joe Average). 
Perhaps the app can save every folder it saved images in the past and search there for lost images. 
If found you can silently add to the list and upload them. 
Or you can ask the user "i found 866 images from this app on your phone. Should i move them to the current folder?".

**Comment by pbb72** [comment]
@peterneubauer, that is a possibility, but like you said, different devices have different file layouts. You would need to document all possible storage locations. While the app itself would only have to go through the previously used storage locations.
